services:
  app:
    build: .
    volumes:
      - .:/var/www/html
      - ./.env:/var/www/html/.env
      - storage:/var/www/html/storage
    depends_on:
      mysql:
        condition: service_healthy
    networks:
      - laravel-network
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost/health" ]
      interval: 30s
      timeout: 10s
      retries: 3

  queue:
    build: .
    command: php artisan queue:work --tries=3 --timeout=90
    volumes:
      - .:/var/www/html
    depends_on:
      app:
        condition: service_started
      mysql:
        condition: service_healthy
    networks:
      - laravel-network
    restart: always

  scheduler:
    build: .
    command: sh -c "while true; do php artisan schedule:run --verbose --no-interaction; sleep 60; done"
    volumes:
      - .:/var/www/html
    depends_on:
      app:
        condition: service_started
      mysql:
        condition: service_healthy
    networks:
      - laravel-network
    restart: always

  mysql:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    volumes:
      - mysql:/var/lib/mysql
    networks:
      - laravel-network
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      interval: 10s
      timeout: 5s
      retries: 3

volumes:
  mysql:
  storage:

networks:
  laravel-network:
    driver: bridge
